#!/bin/sh

# Install DHCS Engineering Tools
# Run with
# bash <(curl -fsSL https://raw.githubusercontent.com/ca-mmis/mdm/PAT-298-base-configuration/install)

echo "Installing Homebrew package manager"
echo "Also installs Xcode Command Line Tools" 
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"