#!/bin/sh

# Install DHCS Engineering Tools
# IMPORTANT: Run sudo bash before running this script when manually provisioning a MacBook
#           When running from JAMF sudo is not needed
# bash <(curl -fsSL https://raw.githubusercontent.com/ca-mmis/mdm/PAT-298-base-configuration/install)

echo "Installing Homebrew package manager"
echo "Also installs Xcode Command Line Tools" 

bash <(curl -fsSL https://raw.githubusercontent.com/ca-mmis/jamf-macos-scripts/master/scripts/SplashBuddy/installHomebrew.sh)

